- id: shrimport
  name: Force relative imports to absolute
  description: Convert relative imports to absolute
  entry: shrimport
  language: python
  types: [python]
  additional_dependencies: [libcst>=1.0.0]
