- id: force-absolute-imports
  name: Force relative imports to absolute
  description: Convert relative imports to absolute
  entry: force-absolute-imports
  language: python
  types: [python]
  additional_dependencies: [libcst>=1.0.0]
